# Site settings
title: Manan
email: akshayakamat@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Akshaya's blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: axe_k

# Build settings
markdown: kramdown
collections:
  travel:
    output: true
